print ("\t")
print ("#########")
print ("#\t#")
print ("#\t#")
print ("#\t#")
print ("#\t#")
print ("#\t#")
print ("#########")
print ("\t")
print ("#\t#")
print ("#\t#")
print ("#\t#")
print ("#########")
print ("#\t#")
print ("#\t#")
print ("#\t#", end="\n\n\n")


print ("#########\n#\t#\n#\t#\n#\t#\n#\t#\n#\t#\n#########")
print ("\t")
print ("#\t#\n#\t#\n#\t#\n#########\n#\t#\n#\t#\n#\t#\n", end="\n\n\n")
print ("\t")


print ("#"*9, "\n#\t#"*5, sep="\t")
print ("#"*9, end="\n\n")
print ("\n#\t#"*3, sep="\t")
print ("#"*9)
print ("#\t#\n"*3, sep="\t")